### ISSUE TITLE
[ArrayIndexOutOfBoundsException] Index 1 out of bounds

### ISSUE THREAD

**Issue by MaximeHoude** [kitaharalab/piano-ballad-arrangement#1]
Hi,

First of all, thank you very much for translating the project! I truly appreciate!

The midi samples work great, but I came across this error with my own midis:
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at PianoBallad.<init>(PianoBallad.java:55)
        at PianoBallad.main(PianoBallad.java:40)
```

The number of bars are under 70 and I tried changing setting the velocity all equal (just like your samples), but that changed nothing. I can't upload a .mid file as an attachment, but here's what the track looks like:
![MidiTrack](https://user-images.githubusercontent.com/87776422/165131673-ae6c854c-6006-4042-a8aa-70a8e3b0beb9.JPG)

Thanks in advance!

**Comment by MaximeHoude** [comment]
Issue related to the way I was processing midi. I used a simple macro to export in midi. 👌
